// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nikita5637/quiz-registrator-api/internal/pkg/model"
)

// Croupier is an autogenerated mock type for the Croupier type
type Croupier struct {
	mock.Mock
}

type Croupier_Expecter struct {
	mock *mock.Mock
}

func (_m *Croupier) EXPECT() *Croupier_Expecter {
	return &Croupier_Expecter{mock: &_m.Mock}
}

// GetGamesWithActiveLottery provides a mock function with given fields: ctx
func (_m *Croupier) GetGamesWithActiveLottery(ctx context.Context) ([]model.Game, error) {
	ret := _m.Called(ctx)

	var r0 []model.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Game, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Game); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Croupier_GetGamesWithActiveLottery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGamesWithActiveLottery'
type Croupier_GetGamesWithActiveLottery_Call struct {
	*mock.Call
}

// GetGamesWithActiveLottery is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Croupier_Expecter) GetGamesWithActiveLottery(ctx interface{}) *Croupier_GetGamesWithActiveLottery_Call {
	return &Croupier_GetGamesWithActiveLottery_Call{Call: _e.mock.On("GetGamesWithActiveLottery", ctx)}
}

func (_c *Croupier_GetGamesWithActiveLottery_Call) Run(run func(ctx context.Context)) *Croupier_GetGamesWithActiveLottery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Croupier_GetGamesWithActiveLottery_Call) Return(_a0 []model.Game, _a1 error) *Croupier_GetGamesWithActiveLottery_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Croupier_GetGamesWithActiveLottery_Call) RunAndReturn(run func(context.Context) ([]model.Game, error)) *Croupier_GetGamesWithActiveLottery_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewCroupier interface {
	mock.TestingT
	Cleanup(func())
}

// NewCroupier creates a new instance of Croupier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCroupier(t mockConstructorTestingTNewCroupier) *Croupier {
	mock := &Croupier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
