#Log level
log_level = "info"
elastic_address = "localhost"
elastic_port = 9200
elastic_index = "quiz_registrator_api_prod"
elastic_logs_enabled = true

#
# Registrator settings
#
bind_address = "localhost"
bind_port = 8080
active_game_lag = 3600
# lottery starts 3600 seconds before the game start
lottery_starts_before = 3600

#
# Reminder settings
#
rabbitmq_address = "localhost"
rabbitmq_port = 5672
rabbitmq_game_reminder_queue_name = "quiz_game_reminder_prod"
rabbitmq_lottery_reminder_queue_name = "quiz_lottery_reminder_prod"
rabbitmq_username = "quiz_reminder"

#
# DB Settings
#
driver = "mysql"
database_address = "localhost"
database_name = "quiz_registrator_api_prod"
database_port = 3306
database_username = "quiz_prod"
