[apiserver]
  [apiserver.bind]
  address = "localhost"
  port = 8080

[croupier]
lottery_starts_before = 3600

[database]
address = "database"
dbname = "registrator_api"
driver = "mysql"
port = 3306
  [database.credentials]
  username = "quiz_regbot"
  password = "TOPSECRET"

[log]
level = "info"
module_name = "registrator-api"
  [log.elastic]
  address = "elasticsearch"
  enabled = true
  index = "quiz_regbot"
  port = 9200

[remind_manager]
  [remind_manager.game.queue]
  name = "game_reminder"
  [remind_manager.lottery.queue]
  name = "lottery_reminder"
  [remind_manager.rabbitmq]
  address = "rabbitmq"
  port = 5672
    [remind_manager.rabbitmq.credentials]
    username = "quiz_regbot"
    password = "TOPSECRET"

[service]
  [service.game]
  has_passed_game_lag = 3600
    [service.game.ics]
      [service.game.ics.queue]
      name = "ics"