version: "3.9"

services:
  registrator-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_PATH: https://github.com/nikita5637/quiz-registrator-api.git
        BRANCH: v1.4
    command: "/bin/registrator-api --config /etc/config.toml"
    container_name: registrator-api
    environment:
      DATABASE_PASSWORD: quiz_regbot
      RABBITMQ_PASSWORD: quiz_regbot
    networks:
      - network
    ports:
      - "8080:8080"

networks:
  network:
    driver: bridge