package model

const (
	// GameTypeClassic ...
	GameTypeClassic int32 = 1
	// GameTypeThematic ...
	GameTypeThematic int32 = 2
	// GameTypeMoviesAndMusic ...
	GameTypeMoviesAndMusic int32 = 5
	// GameTypeClosed ...
	GameTypeClosed int32 = 6
)
