package model

// GameType ...
type GameType int32

const (
	// GameTypeInvalid ...
	GameTypeInvalid GameType = 0
	// GameTypeClassic ...
	GameTypeClassic GameType = 1
	// GameTypeThematic ...
	GameTypeThematic GameType = 2
	// GameTypeEnglish ...
	GameTypeEnglish GameType = 4
	// GameTypeMoviesAndMusic ...
	GameTypeMoviesAndMusic GameType = 5
	// GameTypeClosed ...
	GameTypeClosed GameType = 6
	// GameTypeThematicMoviesAndMusic ...
	GameTypeThematicMoviesAndMusic GameType = 9
)
