package model

// PaymentType ...
type PaymentType int32

const (
	// PaymentInvalid ...
	PaymentInvalid PaymentType = iota
	// PaymentCash ...
	PaymentCash
	// PaymentCertificate ...
	PaymentCertificate
	// PaymentMixed ...
	PaymentMixed
)
