package model

// api/registrator/registrator.proto

// UserState ...
type UserState int32

const (
	// UserStateInvalid ...
	UserStateInvalid UserState = iota
	// UserStateWelcome ...
	UserStateWelcome
	// UserStateRegistered ...
	UserStateRegistered
	// UserStateChangingEmail ...
	UserStateChangingEmail
	// UserStateChangingName ...
	UserStateChangingName
	// UserStateChangingPhone ...
	UserStateChangingPhone
	// UserStateBanned ...
	UserStateBanned
	// ...

	// UserStatesNumber ...
	UserStatesNumber
)
