package quizlogger

const (
	// CreationActionID ...
	CreationActionID = iota + 1
	// ReadingActionID ...
	ReadingActionID
	// UpdatingActionID ...
	UpdatingActionID
	// DeletingActionID ...
	DeletingActionID
)
