// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nikita5637/quiz-registrator-api/internal/pkg/model"
)

// LotteryRegistrator is an autogenerated mock type for the LotteryRegistrator type
type LotteryRegistrator struct {
	mock.Mock
}

type LotteryRegistrator_Expecter struct {
	mock *mock.Mock
}

func (_m *LotteryRegistrator) EXPECT() *LotteryRegistrator_Expecter {
	return &LotteryRegistrator_Expecter{mock: &_m.Mock}
}

// RegisterForLottery provides a mock function with given fields: ctx, game, user
func (_m *LotteryRegistrator) RegisterForLottery(ctx context.Context, game model.Game, user model.User) (int32, error) {
	ret := _m.Called(ctx, game, user)

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Game, model.User) (int32, error)); ok {
		return rf(ctx, game, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Game, model.User) int32); ok {
		r0 = rf(ctx, game, user)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Game, model.User) error); ok {
		r1 = rf(ctx, game, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LotteryRegistrator_RegisterForLottery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterForLottery'
type LotteryRegistrator_RegisterForLottery_Call struct {
	*mock.Call
}

// RegisterForLottery is a helper method to define mock.On call
//   - ctx context.Context
//   - game model.Game
//   - user model.User
func (_e *LotteryRegistrator_Expecter) RegisterForLottery(ctx interface{}, game interface{}, user interface{}) *LotteryRegistrator_RegisterForLottery_Call {
	return &LotteryRegistrator_RegisterForLottery_Call{Call: _e.mock.On("RegisterForLottery", ctx, game, user)}
}

func (_c *LotteryRegistrator_RegisterForLottery_Call) Run(run func(ctx context.Context, game model.Game, user model.User)) *LotteryRegistrator_RegisterForLottery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Game), args[2].(model.User))
	})
	return _c
}

func (_c *LotteryRegistrator_RegisterForLottery_Call) Return(_a0 int32, _a1 error) *LotteryRegistrator_RegisterForLottery_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LotteryRegistrator_RegisterForLottery_Call) RunAndReturn(run func(context.Context, model.Game, model.User) (int32, error)) *LotteryRegistrator_RegisterForLottery_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewLotteryRegistrator interface {
	mock.TestingT
	Cleanup(func())
}

// NewLotteryRegistrator creates a new instance of LotteryRegistrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLotteryRegistrator(t mockConstructorTestingTNewLotteryRegistrator) *LotteryRegistrator {
	mock := &LotteryRegistrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
