package mysql

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"

	"github.com/go-xorm/builder"
	"github.com/nikita5637/quiz-registrator-api/internal/pkg/logger"
)

// GamePhoto represents a row from 'game_photo'.
type GamePhoto struct {
	ID        int          `json:"id"`         // id
	FkGameID  int          `json:"fk_game_id"` // fk_game_id
	URL       string       `json:"url"`        // url
	CreatedAt sql.NullTime `json:"created_at"` // created_at
}

// GamePhotoStorage is GamePhoto service implementation
type GamePhotoStorage struct {
	db *sql.DB
}

// NewGamePhotoStorage creates new instance of GamePhotoStorage
func NewGamePhotoStorage(db *sql.DB) *GamePhotoStorage {
	return &GamePhotoStorage{
		db: db,
	}
}

// GetAll returns all records
func (s *GamePhotoStorage) GetAll(ctx context.Context) ([]GamePhoto, error) {
	return s.Find(ctx, nil, "")
}

// Find perform find request by params
func (s *GamePhotoStorage) Find(ctx context.Context, q builder.Cond, sort string) ([]GamePhoto, error) {
	query := `SELECT id, fk_game_id, url, created_at FROM game_photo`

	var args []interface{}

	if q != nil {
		var where string
		var err error
		where, args, err = builder.ToSQL(q)
		if err != nil {
			return nil, err
		}
		query += ` WHERE ` + where
	}

	if sort != "" {
		query += ` ` + getOrderStmt(sort)
	}

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []GamePhoto

	for rows.Next() {
		var item GamePhoto
		if err := rows.Scan(
			&item.ID,
			&item.FkGameID,
			&item.URL,
			&item.CreatedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, item)
	}

	return items, nil
}

// FindWithLimit perform find request by params, offset and limit
func (s *GamePhotoStorage) FindWithLimit(ctx context.Context, q builder.Cond, sort string, offset, limit uint64) ([]GamePhoto, error) {
	query := `SELECT id, fk_game_id, url, created_at FROM game_photo`

	var args []interface{}

	if q != nil {
		var where string
		var err error
		where, args, err = builder.ToSQL(q)
		if err != nil {
			return nil, err
		}
		query += ` WHERE ` + where
	}

	if sort != "" {
		query += ` ` + getOrderStmt(sort)
	}

	if limit != 0 {
		query += ` OFFSET ? LIMIT ?`
		args = append(args, offset)
		args = append(args, limit)
	}

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []GamePhoto

	for rows.Next() {
		var item GamePhoto
		if err := rows.Scan(
			&item.ID,
			&item.FkGameID,
			&item.URL,
			&item.CreatedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, item)
	}

	return items, nil
}

// Total return count(*) by params
func (s *GamePhotoStorage) Total(ctx context.Context, q builder.Cond) (uint64, error) {
	query := `SELECT count(*) FROM game_photo`

	var args []interface{}

	if q != nil {
		var where string
		var err error
		where, args, err = builder.ToSQL(q)
		if err != nil {
			return 0, err
		}
		query += ` WHERE ` + where
	}

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	defer rows.Close()

	var count uint64

	for rows.Next() {
		if err := rows.Scan(
			&count,
		); err != nil {
			return 0, err
		}
	}

	return count, nil
}

// Insert inserts the GamePhoto to the database.
func (s *GamePhotoStorage) Insert(ctx context.Context, item GamePhoto) (int, error) {
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO game_photo (` +
		`fk_game_id, url, created_at` +
		`) VALUES (` +
		`?, ?, UTC_TIMESTAMP()` +
		`)`
	// run
	logger.Debugf(ctx, sqlstr, item.FkGameID, item.URL)

	res, err := s.db.ExecContext(ctx, sqlstr, item.FkGameID, item.URL)
	if err != nil {
		return 0, err
	}
	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return 0, err
	}

	return int(id), nil
}

// Update updates a GamePhoto in the database.
func (s *GamePhotoStorage) Update(ctx context.Context, item GamePhoto) error {
	// update with primary key
	const sqlstr = `UPDATE game_photo SET ` +
		`fk_game_id = ?, url = ? ` +
		`WHERE id = ?`
	// run
	logger.Debugf(ctx, sqlstr, item.FkGameID, item.URL, item.ID)
	if _, err := s.db.ExecContext(ctx, sqlstr, item.FkGameID, item.URL, item.ID); err != nil {
		return err
	}

	return nil
}

// Upsert performs an upsert for GamePhoto.
func (s *GamePhotoStorage) Upsert(ctx context.Context, item GamePhoto) error {
	// upsert
	const sqlstr = `INSERT INTO game_photo (` +
		`id, fk_game_id, url, created_at` +
		`) VALUES (` +
		`?, ?, ?, UTC_TIMESTAMP()` +
		`)` +
		` ON DUPLICATE KEY UPDATE ` +
		`fk_game_id = VALUES(fk_game_id), url = VALUES(url), created_at = VALUES(created_at)`
	// run
	logger.Debugf(ctx, sqlstr, item.ID, item.FkGameID, item.URL, item.CreatedAt)
	if _, err := s.db.ExecContext(ctx, sqlstr, item.ID, item.FkGameID, item.URL); err != nil {
		return err
	}

	return nil
}

// Delete deletes the GamePhoto from the database.
func (s *GamePhotoStorage) Delete(ctx context.Context, id int) error {
	// delete with single primary key
	const sqlstr = `DELETE FROM game_photo ` +
		`WHERE id = ?`
	// run
	logger.Debugf(ctx, sqlstr, id)

	if _, err := s.db.ExecContext(ctx, sqlstr, id); err != nil {
		return err
	}

	return nil
}

// GetGamePhotoByFkGameID retrieves a row from 'game_photo' as a GamePhoto.
//
// Generated from index 'fk_game_id'.
func (s *GamePhotoStorage) GetGamePhotoByFkGameID(ctx context.Context, fkGameID int) ([]*GamePhoto, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, fk_game_id, url, created_at ` +
		`FROM game_photo ` +
		`WHERE fk_game_id = ?`
	// run
	logger.Debugf(ctx, sqlstr, fkGameID)
	rows, err := s.db.QueryContext(ctx, sqlstr, fkGameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	// process
	var res []*GamePhoto
	for rows.Next() {
		gp := GamePhoto{}
		// scan
		if err := rows.Scan(&gp.ID, &gp.FkGameID, &gp.URL, &gp.CreatedAt); err != nil {
			return nil, err
		}
		res = append(res, &gp)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return res, nil
}

// GetGamePhotoByID retrieves a row from 'game_photo' as a GamePhoto.
//
// Generated from index 'game_photo_id_pkey'.
func (s *GamePhotoStorage) GetGamePhotoByID(ctx context.Context, id int) (*GamePhoto, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, fk_game_id, url, created_at ` +
		`FROM game_photo ` +
		`WHERE id = ?`
	// run
	logger.Debugf(ctx, sqlstr, id)
	gp := GamePhoto{}
	if err := s.db.QueryRowContext(ctx, sqlstr, id).Scan(&gp.ID, &gp.FkGameID, &gp.URL, &gp.CreatedAt); err != nil {
		return nil, err
	}
	return &gp, nil
}
