// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nikita5637/quiz-registrator-api/internal/pkg/model"
)

// GamePlayersFacade is an autogenerated mock type for the GamePlayersFacade type
type GamePlayersFacade struct {
	mock.Mock
}

type GamePlayersFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *GamePlayersFacade) EXPECT() *GamePlayersFacade_Expecter {
	return &GamePlayersFacade_Expecter{mock: &_m.Mock}
}

// CreateGamePlayer provides a mock function with given fields: ctx, gamePlayer
func (_m *GamePlayersFacade) CreateGamePlayer(ctx context.Context, gamePlayer model.GamePlayer) (model.GamePlayer, error) {
	ret := _m.Called(ctx, gamePlayer)

	var r0 model.GamePlayer
	if rf, ok := ret.Get(0).(func(context.Context, model.GamePlayer) model.GamePlayer); ok {
		r0 = rf(ctx, gamePlayer)
	} else {
		r0 = ret.Get(0).(model.GamePlayer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.GamePlayer) error); ok {
		r1 = rf(ctx, gamePlayer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GamePlayersFacade_CreateGamePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGamePlayer'
type GamePlayersFacade_CreateGamePlayer_Call struct {
	*mock.Call
}

// CreateGamePlayer is a helper method to define mock.On call
//  - ctx context.Context
//  - gamePlayer model.GamePlayer
func (_e *GamePlayersFacade_Expecter) CreateGamePlayer(ctx interface{}, gamePlayer interface{}) *GamePlayersFacade_CreateGamePlayer_Call {
	return &GamePlayersFacade_CreateGamePlayer_Call{Call: _e.mock.On("CreateGamePlayer", ctx, gamePlayer)}
}

func (_c *GamePlayersFacade_CreateGamePlayer_Call) Run(run func(ctx context.Context, gamePlayer model.GamePlayer)) *GamePlayersFacade_CreateGamePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.GamePlayer))
	})
	return _c
}

func (_c *GamePlayersFacade_CreateGamePlayer_Call) Return(_a0 model.GamePlayer, _a1 error) *GamePlayersFacade_CreateGamePlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DeleteGamePlayer provides a mock function with given fields: ctx, id
func (_m *GamePlayersFacade) DeleteGamePlayer(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GamePlayersFacade_DeleteGamePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGamePlayer'
type GamePlayersFacade_DeleteGamePlayer_Call struct {
	*mock.Call
}

// DeleteGamePlayer is a helper method to define mock.On call
//  - ctx context.Context
//  - id int32
func (_e *GamePlayersFacade_Expecter) DeleteGamePlayer(ctx interface{}, id interface{}) *GamePlayersFacade_DeleteGamePlayer_Call {
	return &GamePlayersFacade_DeleteGamePlayer_Call{Call: _e.mock.On("DeleteGamePlayer", ctx, id)}
}

func (_c *GamePlayersFacade_DeleteGamePlayer_Call) Run(run func(ctx context.Context, id int32)) *GamePlayersFacade_DeleteGamePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *GamePlayersFacade_DeleteGamePlayer_Call) Return(_a0 error) *GamePlayersFacade_DeleteGamePlayer_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetGamePlayer provides a mock function with given fields: ctx, id
func (_m *GamePlayersFacade) GetGamePlayer(ctx context.Context, id int32) (model.GamePlayer, error) {
	ret := _m.Called(ctx, id)

	var r0 model.GamePlayer
	if rf, ok := ret.Get(0).(func(context.Context, int32) model.GamePlayer); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.GamePlayer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GamePlayersFacade_GetGamePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGamePlayer'
type GamePlayersFacade_GetGamePlayer_Call struct {
	*mock.Call
}

// GetGamePlayer is a helper method to define mock.On call
//  - ctx context.Context
//  - id int32
func (_e *GamePlayersFacade_Expecter) GetGamePlayer(ctx interface{}, id interface{}) *GamePlayersFacade_GetGamePlayer_Call {
	return &GamePlayersFacade_GetGamePlayer_Call{Call: _e.mock.On("GetGamePlayer", ctx, id)}
}

func (_c *GamePlayersFacade_GetGamePlayer_Call) Run(run func(ctx context.Context, id int32)) *GamePlayersFacade_GetGamePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *GamePlayersFacade_GetGamePlayer_Call) Return(_a0 model.GamePlayer, _a1 error) *GamePlayersFacade_GetGamePlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetGamePlayersByFields provides a mock function with given fields: ctx, gamePlayer
func (_m *GamePlayersFacade) GetGamePlayersByFields(ctx context.Context, gamePlayer model.GamePlayer) ([]model.GamePlayer, error) {
	ret := _m.Called(ctx, gamePlayer)

	var r0 []model.GamePlayer
	if rf, ok := ret.Get(0).(func(context.Context, model.GamePlayer) []model.GamePlayer); ok {
		r0 = rf(ctx, gamePlayer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GamePlayer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.GamePlayer) error); ok {
		r1 = rf(ctx, gamePlayer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GamePlayersFacade_GetGamePlayersByFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGamePlayersByFields'
type GamePlayersFacade_GetGamePlayersByFields_Call struct {
	*mock.Call
}

// GetGamePlayersByFields is a helper method to define mock.On call
//  - ctx context.Context
//  - gamePlayer model.GamePlayer
func (_e *GamePlayersFacade_Expecter) GetGamePlayersByFields(ctx interface{}, gamePlayer interface{}) *GamePlayersFacade_GetGamePlayersByFields_Call {
	return &GamePlayersFacade_GetGamePlayersByFields_Call{Call: _e.mock.On("GetGamePlayersByFields", ctx, gamePlayer)}
}

func (_c *GamePlayersFacade_GetGamePlayersByFields_Call) Run(run func(ctx context.Context, gamePlayer model.GamePlayer)) *GamePlayersFacade_GetGamePlayersByFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.GamePlayer))
	})
	return _c
}

func (_c *GamePlayersFacade_GetGamePlayersByFields_Call) Return(_a0 []model.GamePlayer, _a1 error) *GamePlayersFacade_GetGamePlayersByFields_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetGamePlayersByGameID provides a mock function with given fields: ctx, gameID
func (_m *GamePlayersFacade) GetGamePlayersByGameID(ctx context.Context, gameID int32) ([]model.GamePlayer, error) {
	ret := _m.Called(ctx, gameID)

	var r0 []model.GamePlayer
	if rf, ok := ret.Get(0).(func(context.Context, int32) []model.GamePlayer); ok {
		r0 = rf(ctx, gameID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GamePlayer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GamePlayersFacade_GetGamePlayersByGameID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGamePlayersByGameID'
type GamePlayersFacade_GetGamePlayersByGameID_Call struct {
	*mock.Call
}

// GetGamePlayersByGameID is a helper method to define mock.On call
//  - ctx context.Context
//  - gameID int32
func (_e *GamePlayersFacade_Expecter) GetGamePlayersByGameID(ctx interface{}, gameID interface{}) *GamePlayersFacade_GetGamePlayersByGameID_Call {
	return &GamePlayersFacade_GetGamePlayersByGameID_Call{Call: _e.mock.On("GetGamePlayersByGameID", ctx, gameID)}
}

func (_c *GamePlayersFacade_GetGamePlayersByGameID_Call) Run(run func(ctx context.Context, gameID int32)) *GamePlayersFacade_GetGamePlayersByGameID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *GamePlayersFacade_GetGamePlayersByGameID_Call) Return(_a0 []model.GamePlayer, _a1 error) *GamePlayersFacade_GetGamePlayersByGameID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetUserGameIDs provides a mock function with given fields: ctx, userID
func (_m *GamePlayersFacade) GetUserGameIDs(ctx context.Context, userID int32) ([]int32, error) {
	ret := _m.Called(ctx, userID)

	var r0 []int32
	if rf, ok := ret.Get(0).(func(context.Context, int32) []int32); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int32)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GamePlayersFacade_GetUserGameIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGameIDs'
type GamePlayersFacade_GetUserGameIDs_Call struct {
	*mock.Call
}

// GetUserGameIDs is a helper method to define mock.On call
//  - ctx context.Context
//  - userID int32
func (_e *GamePlayersFacade_Expecter) GetUserGameIDs(ctx interface{}, userID interface{}) *GamePlayersFacade_GetUserGameIDs_Call {
	return &GamePlayersFacade_GetUserGameIDs_Call{Call: _e.mock.On("GetUserGameIDs", ctx, userID)}
}

func (_c *GamePlayersFacade_GetUserGameIDs_Call) Run(run func(ctx context.Context, userID int32)) *GamePlayersFacade_GetUserGameIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *GamePlayersFacade_GetUserGameIDs_Call) Return(_a0 []int32, _a1 error) *GamePlayersFacade_GetUserGameIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// PatchGamePlayer provides a mock function with given fields: ctx, gamePlayer
func (_m *GamePlayersFacade) PatchGamePlayer(ctx context.Context, gamePlayer model.GamePlayer) (model.GamePlayer, error) {
	ret := _m.Called(ctx, gamePlayer)

	var r0 model.GamePlayer
	if rf, ok := ret.Get(0).(func(context.Context, model.GamePlayer) model.GamePlayer); ok {
		r0 = rf(ctx, gamePlayer)
	} else {
		r0 = ret.Get(0).(model.GamePlayer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.GamePlayer) error); ok {
		r1 = rf(ctx, gamePlayer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GamePlayersFacade_PatchGamePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchGamePlayer'
type GamePlayersFacade_PatchGamePlayer_Call struct {
	*mock.Call
}

// PatchGamePlayer is a helper method to define mock.On call
//  - ctx context.Context
//  - gamePlayer model.GamePlayer
func (_e *GamePlayersFacade_Expecter) PatchGamePlayer(ctx interface{}, gamePlayer interface{}) *GamePlayersFacade_PatchGamePlayer_Call {
	return &GamePlayersFacade_PatchGamePlayer_Call{Call: _e.mock.On("PatchGamePlayer", ctx, gamePlayer)}
}

func (_c *GamePlayersFacade_PatchGamePlayer_Call) Run(run func(ctx context.Context, gamePlayer model.GamePlayer)) *GamePlayersFacade_PatchGamePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.GamePlayer))
	})
	return _c
}

func (_c *GamePlayersFacade_PatchGamePlayer_Call) Return(_a0 model.GamePlayer, _a1 error) *GamePlayersFacade_PatchGamePlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewGamePlayersFacade interface {
	mock.TestingT
	Cleanup(func())
}

// NewGamePlayersFacade creates a new instance of GamePlayersFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGamePlayersFacade(t mockConstructorTestingTNewGamePlayersFacade) *GamePlayersFacade {
	mock := &GamePlayersFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
