// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikita5637/quiz-registrator-api/internal/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// UsersFacade is an autogenerated mock type for the UsersFacade type
type UsersFacade struct {
	mock.Mock
}

type UsersFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *UsersFacade) EXPECT() *UsersFacade_Expecter {
	return &UsersFacade_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *UsersFacade) CreateUser(ctx context.Context, user model.User) (model.User, error) {
	ret := _m.Called(ctx, user)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(context.Context, model.User) model.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersFacade_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UsersFacade_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//  - ctx context.Context
//  - user model.User
func (_e *UsersFacade_Expecter) CreateUser(ctx interface{}, user interface{}) *UsersFacade_CreateUser_Call {
	return &UsersFacade_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *UsersFacade_CreateUser_Call) Run(run func(ctx context.Context, user model.User)) *UsersFacade_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.User))
	})
	return _c
}

func (_c *UsersFacade_CreateUser_Call) Return(_a0 model.User, _a1 error) *UsersFacade_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *UsersFacade) GetUser(ctx context.Context, userID int32) (model.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(context.Context, int32) model.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersFacade_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UsersFacade_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//  - ctx context.Context
//  - userID int32
func (_e *UsersFacade_Expecter) GetUser(ctx interface{}, userID interface{}) *UsersFacade_GetUser_Call {
	return &UsersFacade_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userID)}
}

func (_c *UsersFacade_GetUser_Call) Run(run func(ctx context.Context, userID int32)) *UsersFacade_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *UsersFacade_GetUser_Call) Return(_a0 model.User, _a1 error) *UsersFacade_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetUserByTelegramID provides a mock function with given fields: ctx, telegramID
func (_m *UsersFacade) GetUserByTelegramID(ctx context.Context, telegramID int64) (model.User, error) {
	ret := _m.Called(ctx, telegramID)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.User); ok {
		r0 = rf(ctx, telegramID)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersFacade_GetUserByTelegramID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByTelegramID'
type UsersFacade_GetUserByTelegramID_Call struct {
	*mock.Call
}

// GetUserByTelegramID is a helper method to define mock.On call
//  - ctx context.Context
//  - telegramID int64
func (_e *UsersFacade_Expecter) GetUserByTelegramID(ctx interface{}, telegramID interface{}) *UsersFacade_GetUserByTelegramID_Call {
	return &UsersFacade_GetUserByTelegramID_Call{Call: _e.mock.On("GetUserByTelegramID", ctx, telegramID)}
}

func (_c *UsersFacade_GetUserByTelegramID_Call) Run(run func(ctx context.Context, telegramID int64)) *UsersFacade_GetUserByTelegramID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UsersFacade_GetUserByTelegramID_Call) Return(_a0 model.User, _a1 error) *UsersFacade_GetUserByTelegramID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// PatchUser provides a mock function with given fields: ctx, user, paths
func (_m *UsersFacade) PatchUser(ctx context.Context, user model.User, paths []string) (model.User, error) {
	ret := _m.Called(ctx, user, paths)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(context.Context, model.User, []string) model.User); ok {
		r0 = rf(ctx, user, paths)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.User, []string) error); ok {
		r1 = rf(ctx, user, paths)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersFacade_PatchUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchUser'
type UsersFacade_PatchUser_Call struct {
	*mock.Call
}

// PatchUser is a helper method to define mock.On call
//  - ctx context.Context
//  - user model.User
//  - paths []string
func (_e *UsersFacade_Expecter) PatchUser(ctx interface{}, user interface{}, paths interface{}) *UsersFacade_PatchUser_Call {
	return &UsersFacade_PatchUser_Call{Call: _e.mock.On("PatchUser", ctx, user, paths)}
}

func (_c *UsersFacade_PatchUser_Call) Run(run func(ctx context.Context, user model.User, paths []string)) *UsersFacade_PatchUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.User), args[2].([]string))
	})
	return _c
}

func (_c *UsersFacade_PatchUser_Call) Return(_a0 model.User, _a1 error) *UsersFacade_PatchUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewUsersFacade interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsersFacade creates a new instance of UsersFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsersFacade(t mockConstructorTestingTNewUsersFacade) *UsersFacade {
	mock := &UsersFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
