// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: registrator/registrator.proto

package registrator

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegistratorServiceClient is the client API for RegistratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistratorServiceClient interface {
	// AddGame creates a new game
	AddGame(ctx context.Context, in *AddGameRequest, opts ...grpc.CallOption) (*AddGameResponse, error)
	// AddGames inserts a new games. Used by quiz-fetcher
	AddGames(ctx context.Context, in *AddGamesRequest, opts ...grpc.CallOption) (*AddGamesResponse, error)
	// DeleteGame deletes a game by game ID
	DeleteGame(ctx context.Context, in *DeleteGameRequest, opts ...grpc.CallOption) (*DeleteGameResponse, error)
	// Returns game or Not Found
	GetGameByID(ctx context.Context, in *GetGameByIDRequest, opts ...grpc.CallOption) (*GetGameByIDResponse, error)
	// GetGames returns games
	GetGames(ctx context.Context, in *GetGamesRequest, opts ...grpc.CallOption) (*GetGamesResponse, error)
	// GetPlayersByGameID returns list of players by game ID
	GetPlayersByGameID(ctx context.Context, in *GetPlayersByGameIDRequest, opts ...grpc.CallOption) (*GetPlayersByGameIDResponse, error)
	// GetRegisteredGames returns registered games
	GetRegisteredGames(ctx context.Context, in *GetRegisteredGamesRequest, opts ...grpc.CallOption) (*GetRegisteredGamesResponse, error)
	// GetUserGames returns games by user ID
	GetUserGames(ctx context.Context, in *GetUserGamesRequest, opts ...grpc.CallOption) (*GetUserGamesResponse, error)
	// RegisterGame registers game
	RegisterGame(ctx context.Context, in *RegisterGameRequest, opts ...grpc.CallOption) (*RegisterGameResponse, error)
	// RegisterPlayer registers player for a game
	RegisterPlayer(ctx context.Context, in *RegisterPlayerRequest, opts ...grpc.CallOption) (*RegisterPlayerResponse, error)
	// UnregisterGame unregisters game
	UnregisterGame(ctx context.Context, in *UnregisterGameRequest, opts ...grpc.CallOption) (*UnregisterGameResponse, error)
	// UnregisterPlayer unregisters player
	UnregisterPlayer(ctx context.Context, in *UnregisterPlayerRequest, opts ...grpc.CallOption) (*UnregisterPlayerResponse, error)
	// UpdatePayment updates payment
	UpdatePayment(ctx context.Context, in *UpdatePaymentRequest, opts ...grpc.CallOption) (*UpdatePaymentResponse, error)
}

type registratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistratorServiceClient(cc grpc.ClientConnInterface) RegistratorServiceClient {
	return &registratorServiceClient{cc}
}

func (c *registratorServiceClient) AddGame(ctx context.Context, in *AddGameRequest, opts ...grpc.CallOption) (*AddGameResponse, error) {
	out := new(AddGameResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/AddGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registratorServiceClient) AddGames(ctx context.Context, in *AddGamesRequest, opts ...grpc.CallOption) (*AddGamesResponse, error) {
	out := new(AddGamesResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/AddGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registratorServiceClient) DeleteGame(ctx context.Context, in *DeleteGameRequest, opts ...grpc.CallOption) (*DeleteGameResponse, error) {
	out := new(DeleteGameResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/DeleteGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registratorServiceClient) GetGameByID(ctx context.Context, in *GetGameByIDRequest, opts ...grpc.CallOption) (*GetGameByIDResponse, error) {
	out := new(GetGameByIDResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/GetGameByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registratorServiceClient) GetGames(ctx context.Context, in *GetGamesRequest, opts ...grpc.CallOption) (*GetGamesResponse, error) {
	out := new(GetGamesResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/GetGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registratorServiceClient) GetPlayersByGameID(ctx context.Context, in *GetPlayersByGameIDRequest, opts ...grpc.CallOption) (*GetPlayersByGameIDResponse, error) {
	out := new(GetPlayersByGameIDResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/GetPlayersByGameID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registratorServiceClient) GetRegisteredGames(ctx context.Context, in *GetRegisteredGamesRequest, opts ...grpc.CallOption) (*GetRegisteredGamesResponse, error) {
	out := new(GetRegisteredGamesResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/GetRegisteredGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registratorServiceClient) GetUserGames(ctx context.Context, in *GetUserGamesRequest, opts ...grpc.CallOption) (*GetUserGamesResponse, error) {
	out := new(GetUserGamesResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/GetUserGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registratorServiceClient) RegisterGame(ctx context.Context, in *RegisterGameRequest, opts ...grpc.CallOption) (*RegisterGameResponse, error) {
	out := new(RegisterGameResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/RegisterGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registratorServiceClient) RegisterPlayer(ctx context.Context, in *RegisterPlayerRequest, opts ...grpc.CallOption) (*RegisterPlayerResponse, error) {
	out := new(RegisterPlayerResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/RegisterPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registratorServiceClient) UnregisterGame(ctx context.Context, in *UnregisterGameRequest, opts ...grpc.CallOption) (*UnregisterGameResponse, error) {
	out := new(UnregisterGameResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/UnregisterGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registratorServiceClient) UnregisterPlayer(ctx context.Context, in *UnregisterPlayerRequest, opts ...grpc.CallOption) (*UnregisterPlayerResponse, error) {
	out := new(UnregisterPlayerResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/UnregisterPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registratorServiceClient) UpdatePayment(ctx context.Context, in *UpdatePaymentRequest, opts ...grpc.CallOption) (*UpdatePaymentResponse, error) {
	out := new(UpdatePaymentResponse)
	err := c.cc.Invoke(ctx, "/registrator.RegistratorService/UpdatePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistratorServiceServer is the server API for RegistratorService service.
// All implementations must embed UnimplementedRegistratorServiceServer
// for forward compatibility
type RegistratorServiceServer interface {
	// AddGame creates a new game
	AddGame(context.Context, *AddGameRequest) (*AddGameResponse, error)
	// AddGames inserts a new games. Used by quiz-fetcher
	AddGames(context.Context, *AddGamesRequest) (*AddGamesResponse, error)
	// DeleteGame deletes a game by game ID
	DeleteGame(context.Context, *DeleteGameRequest) (*DeleteGameResponse, error)
	// Returns game or Not Found
	GetGameByID(context.Context, *GetGameByIDRequest) (*GetGameByIDResponse, error)
	// GetGames returns games
	GetGames(context.Context, *GetGamesRequest) (*GetGamesResponse, error)
	// GetPlayersByGameID returns list of players by game ID
	GetPlayersByGameID(context.Context, *GetPlayersByGameIDRequest) (*GetPlayersByGameIDResponse, error)
	// GetRegisteredGames returns registered games
	GetRegisteredGames(context.Context, *GetRegisteredGamesRequest) (*GetRegisteredGamesResponse, error)
	// GetUserGames returns games by user ID
	GetUserGames(context.Context, *GetUserGamesRequest) (*GetUserGamesResponse, error)
	// RegisterGame registers game
	RegisterGame(context.Context, *RegisterGameRequest) (*RegisterGameResponse, error)
	// RegisterPlayer registers player for a game
	RegisterPlayer(context.Context, *RegisterPlayerRequest) (*RegisterPlayerResponse, error)
	// UnregisterGame unregisters game
	UnregisterGame(context.Context, *UnregisterGameRequest) (*UnregisterGameResponse, error)
	// UnregisterPlayer unregisters player
	UnregisterPlayer(context.Context, *UnregisterPlayerRequest) (*UnregisterPlayerResponse, error)
	// UpdatePayment updates payment
	UpdatePayment(context.Context, *UpdatePaymentRequest) (*UpdatePaymentResponse, error)
	mustEmbedUnimplementedRegistratorServiceServer()
}

// UnimplementedRegistratorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRegistratorServiceServer struct {
}

func (UnimplementedRegistratorServiceServer) AddGame(context.Context, *AddGameRequest) (*AddGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGame not implemented")
}
func (UnimplementedRegistratorServiceServer) AddGames(context.Context, *AddGamesRequest) (*AddGamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGames not implemented")
}
func (UnimplementedRegistratorServiceServer) DeleteGame(context.Context, *DeleteGameRequest) (*DeleteGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGame not implemented")
}
func (UnimplementedRegistratorServiceServer) GetGameByID(context.Context, *GetGameByIDRequest) (*GetGameByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameByID not implemented")
}
func (UnimplementedRegistratorServiceServer) GetGames(context.Context, *GetGamesRequest) (*GetGamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGames not implemented")
}
func (UnimplementedRegistratorServiceServer) GetPlayersByGameID(context.Context, *GetPlayersByGameIDRequest) (*GetPlayersByGameIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayersByGameID not implemented")
}
func (UnimplementedRegistratorServiceServer) GetRegisteredGames(context.Context, *GetRegisteredGamesRequest) (*GetRegisteredGamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegisteredGames not implemented")
}
func (UnimplementedRegistratorServiceServer) GetUserGames(context.Context, *GetUserGamesRequest) (*GetUserGamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGames not implemented")
}
func (UnimplementedRegistratorServiceServer) RegisterGame(context.Context, *RegisterGameRequest) (*RegisterGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterGame not implemented")
}
func (UnimplementedRegistratorServiceServer) RegisterPlayer(context.Context, *RegisterPlayerRequest) (*RegisterPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPlayer not implemented")
}
func (UnimplementedRegistratorServiceServer) UnregisterGame(context.Context, *UnregisterGameRequest) (*UnregisterGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterGame not implemented")
}
func (UnimplementedRegistratorServiceServer) UnregisterPlayer(context.Context, *UnregisterPlayerRequest) (*UnregisterPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterPlayer not implemented")
}
func (UnimplementedRegistratorServiceServer) UpdatePayment(context.Context, *UpdatePaymentRequest) (*UpdatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePayment not implemented")
}
func (UnimplementedRegistratorServiceServer) mustEmbedUnimplementedRegistratorServiceServer() {}

// UnsafeRegistratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistratorServiceServer will
// result in compilation errors.
type UnsafeRegistratorServiceServer interface {
	mustEmbedUnimplementedRegistratorServiceServer()
}

func RegisterRegistratorServiceServer(s grpc.ServiceRegistrar, srv RegistratorServiceServer) {
	s.RegisterService(&RegistratorService_ServiceDesc, srv)
}

func _RegistratorService_AddGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).AddGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/AddGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).AddGame(ctx, req.(*AddGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistratorService_AddGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).AddGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/AddGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).AddGames(ctx, req.(*AddGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistratorService_DeleteGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).DeleteGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/DeleteGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).DeleteGame(ctx, req.(*DeleteGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistratorService_GetGameByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).GetGameByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/GetGameByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).GetGameByID(ctx, req.(*GetGameByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistratorService_GetGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).GetGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/GetGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).GetGames(ctx, req.(*GetGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistratorService_GetPlayersByGameID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayersByGameIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).GetPlayersByGameID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/GetPlayersByGameID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).GetPlayersByGameID(ctx, req.(*GetPlayersByGameIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistratorService_GetRegisteredGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegisteredGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).GetRegisteredGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/GetRegisteredGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).GetRegisteredGames(ctx, req.(*GetRegisteredGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistratorService_GetUserGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).GetUserGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/GetUserGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).GetUserGames(ctx, req.(*GetUserGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistratorService_RegisterGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).RegisterGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/RegisterGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).RegisterGame(ctx, req.(*RegisterGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistratorService_RegisterPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).RegisterPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/RegisterPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).RegisterPlayer(ctx, req.(*RegisterPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistratorService_UnregisterGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).UnregisterGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/UnregisterGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).UnregisterGame(ctx, req.(*UnregisterGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistratorService_UnregisterPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).UnregisterPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/UnregisterPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).UnregisterPlayer(ctx, req.(*UnregisterPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistratorService_UpdatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServiceServer).UpdatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrator.RegistratorService/UpdatePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServiceServer).UpdatePayment(ctx, req.(*UpdatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistratorService_ServiceDesc is the grpc.ServiceDesc for RegistratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registrator.RegistratorService",
	HandlerType: (*RegistratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGame",
			Handler:    _RegistratorService_AddGame_Handler,
		},
		{
			MethodName: "AddGames",
			Handler:    _RegistratorService_AddGames_Handler,
		},
		{
			MethodName: "DeleteGame",
			Handler:    _RegistratorService_DeleteGame_Handler,
		},
		{
			MethodName: "GetGameByID",
			Handler:    _RegistratorService_GetGameByID_Handler,
		},
		{
			MethodName: "GetGames",
			Handler:    _RegistratorService_GetGames_Handler,
		},
		{
			MethodName: "GetPlayersByGameID",
			Handler:    _RegistratorService_GetPlayersByGameID_Handler,
		},
		{
			MethodName: "GetRegisteredGames",
			Handler:    _RegistratorService_GetRegisteredGames_Handler,
		},
		{
			MethodName: "GetUserGames",
			Handler:    _RegistratorService_GetUserGames_Handler,
		},
		{
			MethodName: "RegisterGame",
			Handler:    _RegistratorService_RegisterGame_Handler,
		},
		{
			MethodName: "RegisterPlayer",
			Handler:    _RegistratorService_RegisterPlayer_Handler,
		},
		{
			MethodName: "UnregisterGame",
			Handler:    _RegistratorService_UnregisterGame_Handler,
		},
		{
			MethodName: "UnregisterPlayer",
			Handler:    _RegistratorService_UnregisterPlayer_Handler,
		},
		{
			MethodName: "UpdatePayment",
			Handler:    _RegistratorService_UpdatePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registrator/registrator.proto",
}
