// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: croupier/croupier.proto

package croupier

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLotteryStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int32 `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *GetLotteryStatusRequest) Reset() {
	*x = GetLotteryStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_croupier_croupier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLotteryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotteryStatusRequest) ProtoMessage() {}

func (x *GetLotteryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_croupier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotteryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetLotteryStatusRequest) Descriptor() ([]byte, []int) {
	return file_croupier_croupier_proto_rawDescGZIP(), []int{0}
}

func (x *GetLotteryStatusRequest) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type GetLotteryStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Active bool `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *GetLotteryStatusResponse) Reset() {
	*x = GetLotteryStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_croupier_croupier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLotteryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotteryStatusResponse) ProtoMessage() {}

func (x *GetLotteryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_croupier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotteryStatusResponse.ProtoReflect.Descriptor instead.
func (*GetLotteryStatusResponse) Descriptor() ([]byte, []int) {
	return file_croupier_croupier_proto_rawDescGZIP(), []int{1}
}

func (x *GetLotteryStatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type RegisterForLotteryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int32 `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *RegisterForLotteryRequest) Reset() {
	*x = RegisterForLotteryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_croupier_croupier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterForLotteryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterForLotteryRequest) ProtoMessage() {}

func (x *RegisterForLotteryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_croupier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterForLotteryRequest.ProtoReflect.Descriptor instead.
func (*RegisterForLotteryRequest) Descriptor() ([]byte, []int) {
	return file_croupier_croupier_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterForLotteryRequest) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type RegisterForLotteryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *RegisterForLotteryResponse) Reset() {
	*x = RegisterForLotteryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_croupier_croupier_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterForLotteryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterForLotteryResponse) ProtoMessage() {}

func (x *RegisterForLotteryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_croupier_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterForLotteryResponse.ProtoReflect.Descriptor instead.
func (*RegisterForLotteryResponse) Descriptor() ([]byte, []int) {
	return file_croupier_croupier_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterForLotteryResponse) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_croupier_croupier_proto protoreflect.FileDescriptor

var file_croupier_croupier_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x65, 0x72, 0x2f, 0x63, 0x72, 0x6f, 0x75, 0x70,
	0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x72, 0x6f, 0x75, 0x70,
	0x69, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4c, 0x6f,
	0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x34, 0x0a, 0x19, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x22, 0x34, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x72,
	0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0xc9, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x2e, 0x63, 0x72, 0x6f, 0x75, 0x70, 0x69,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x72, 0x6f,
	0x75, 0x70, 0x69, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x61, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x4c,
	0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x12, 0x23, 0x2e, 0x63, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x4c, 0x6f, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x72,
	0x6f, 0x75, 0x70, 0x69, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46,
	0x6f, 0x72, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x69, 0x6b, 0x69, 0x74, 0x61, 0x35, 0x36, 0x33, 0x37, 0x2f, 0x71, 0x75, 0x69,
	0x7a, 0x2d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2d, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x65,
	0x72, 0x3b, 0x63, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_croupier_croupier_proto_rawDescOnce sync.Once
	file_croupier_croupier_proto_rawDescData = file_croupier_croupier_proto_rawDesc
)

func file_croupier_croupier_proto_rawDescGZIP() []byte {
	file_croupier_croupier_proto_rawDescOnce.Do(func() {
		file_croupier_croupier_proto_rawDescData = protoimpl.X.CompressGZIP(file_croupier_croupier_proto_rawDescData)
	})
	return file_croupier_croupier_proto_rawDescData
}

var file_croupier_croupier_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_croupier_croupier_proto_goTypes = []interface{}{
	(*GetLotteryStatusRequest)(nil),    // 0: croupier.GetLotteryStatusRequest
	(*GetLotteryStatusResponse)(nil),   // 1: croupier.GetLotteryStatusResponse
	(*RegisterForLotteryRequest)(nil),  // 2: croupier.RegisterForLotteryRequest
	(*RegisterForLotteryResponse)(nil), // 3: croupier.RegisterForLotteryResponse
}
var file_croupier_croupier_proto_depIdxs = []int32{
	0, // 0: croupier.Service.GetLotteryStatus:input_type -> croupier.GetLotteryStatusRequest
	2, // 1: croupier.Service.RegisterForLottery:input_type -> croupier.RegisterForLotteryRequest
	1, // 2: croupier.Service.GetLotteryStatus:output_type -> croupier.GetLotteryStatusResponse
	3, // 3: croupier.Service.RegisterForLottery:output_type -> croupier.RegisterForLotteryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_croupier_croupier_proto_init() }
func file_croupier_croupier_proto_init() {
	if File_croupier_croupier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_croupier_croupier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLotteryStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_croupier_croupier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLotteryStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_croupier_croupier_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterForLotteryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_croupier_croupier_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterForLotteryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_croupier_croupier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_croupier_croupier_proto_goTypes,
		DependencyIndexes: file_croupier_croupier_proto_depIdxs,
		MessageInfos:      file_croupier_croupier_proto_msgTypes,
	}.Build()
	File_croupier_croupier_proto = out.File
	file_croupier_croupier_proto_rawDesc = nil
	file_croupier_croupier_proto_goTypes = nil
	file_croupier_croupier_proto_depIdxs = nil
}
