// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: croupier/croupier.proto

package croupier

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// GetLotteryStatus returns lottery status by game id
	GetLotteryStatus(ctx context.Context, in *GetLotteryStatusRequest, opts ...grpc.CallOption) (*GetLotteryStatusResponse, error)
	// RegisterForLottery registers player for lottery
	RegisterForLottery(ctx context.Context, in *RegisterForLotteryRequest, opts ...grpc.CallOption) (*RegisterForLotteryResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) GetLotteryStatus(ctx context.Context, in *GetLotteryStatusRequest, opts ...grpc.CallOption) (*GetLotteryStatusResponse, error) {
	out := new(GetLotteryStatusResponse)
	err := c.cc.Invoke(ctx, "/croupier.Service/GetLotteryStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) RegisterForLottery(ctx context.Context, in *RegisterForLotteryRequest, opts ...grpc.CallOption) (*RegisterForLotteryResponse, error) {
	out := new(RegisterForLotteryResponse)
	err := c.cc.Invoke(ctx, "/croupier.Service/RegisterForLottery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	// GetLotteryStatus returns lottery status by game id
	GetLotteryStatus(context.Context, *GetLotteryStatusRequest) (*GetLotteryStatusResponse, error)
	// RegisterForLottery registers player for lottery
	RegisterForLottery(context.Context, *RegisterForLotteryRequest) (*RegisterForLotteryResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) GetLotteryStatus(context.Context, *GetLotteryStatusRequest) (*GetLotteryStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLotteryStatus not implemented")
}
func (UnimplementedServiceServer) RegisterForLottery(context.Context, *RegisterForLotteryRequest) (*RegisterForLotteryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterForLottery not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_GetLotteryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLotteryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetLotteryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/croupier.Service/GetLotteryStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetLotteryStatus(ctx, req.(*GetLotteryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_RegisterForLottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterForLotteryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).RegisterForLottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/croupier.Service/RegisterForLottery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).RegisterForLottery(ctx, req.(*RegisterForLotteryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "croupier.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLotteryStatus",
			Handler:    _Service_GetLotteryStatus_Handler,
		},
		{
			MethodName: "RegisterForLottery",
			Handler:    _Service_RegisterForLottery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "croupier/croupier.proto",
}
