package model

const (
	// GameTypeClassic ...
	GameTypeClassic int32 = 1
	// GameTypeThematic ...
	GameTypeThematic int32 = 2
	// GameTypeEnglish ...
	GameTypeEnglish int32 = 4
	// GameTypeMoviesAndMusic ...
	GameTypeMoviesAndMusic int32 = 5
	// GameTypeClosed ...
	GameTypeClosed int32 = 6
	// GameTypeThematicMoviesAndMusic ...
	GameTypeThematicMoviesAndMusic int32 = 9
)
