package model

const (
	// LeagueInvalid ...
	LeagueInvalid int32 = iota
	// LeagueQuizPlease ...
	LeagueQuizPlease
	// LeagueSquiz ...
	LeagueSquiz
	// LeagueSixtySeconds ...
	LeagueSixtySeconds
	// LeagueShaker ...
	LeagueShaker
	// LeagueWOW ...
	LeagueWOW
	// LeagueMozgoboynya ...
	LeagueMozgoboynya

	// Add new leagues here ...

	// NumberOfLeagues ...
	NumberOfLeagues
)
